spring: 
  profiles:  
    active:  prod
  datasource: 
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    max-idle: 8
    min-idle: 5
    initial-size: 10
  jpa: 
    database: MYSQL
    show-sql: true
    open-in-view: true
  properties: 
    hibernate: 
      hbm2ddl: 
        auto: update
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      cache: 
        region: 
          factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
hiernate: 
  show_sql: true
  connection: 
    autocommit: true
  cache: 
    use_second_level_cache: true
    provider_configuration_file_resource_path: ehcache.xml
    use_query_cache: true
net: 
  sf: 
    ehcache: 
      configurationResourceName: net.sf.ehcache.hibernate.EhCacheProvider